# -*- coding: utf-8 -*-
"""testsystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRJ5csmin8QBTdZPZZZGv6ckkjDWCxfb
"""

!pip install streamlit
!pip install openai

# Google Driveと接続を行います。これを行うことで、Driveにあるデータにアクセスできるようになります。
# 下記セルを実行すると、Googleアカウントのログインを求められますのでログインしてください。
from google.colab import drive
drive.mount('/content/drive')

# 作業フォルダへの移動を行います。
# もしアップロードした場所が異なる場合は作業場所を変更してください。
import os
os.chdir('/content/drive/MyDrive/4年セミナー/システム') #ここを変更

# ファイルの表示
from google.colab import files
files.view("test1.py")

# Streamlitを動かす処理
!streamlit run test1.py & sleep 3 && npx localtunnel --port 8501